//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroOrms.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class todo_item
    {
        public long id { get; set; }
        public string name { get; set; }
        public Nullable<bool> is_complete { get; set; }
        public long user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
